#pragma once
#define HASP_DEVICE_TYPE	0x9C40
#define HASP_IOCTL_DOS_INITIALIZE  CTL_CODE(HASP_DEVICE_TYPE, (ULONG)0xA01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HASP_IOCTL_DOS_DISPATCH    CTL_CODE(HASP_DEVICE_TYPE, (ULONG)0xA00, METHOD_BUFFERED, FILE_ANY_ACCESS)
